services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
    depends_on:
      - redpanda
      - chroma
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:2.0.0
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-1433}:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v26.1.14
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
      - --mode dev-container
      - --smp 1
    ports:
      - "19092:19092"
      - "18082:18082"
      - "18081:18081"
      - "9644:9644"
    volumes:
      - redpanda_data:/var/lib/redpanda/data

  chroma:
    image: chromadb/chroma:1.5.3
    ports:
      - "8100:8000"
    volumes:
      - chroma_data:/data

volumes:
  redpanda_data:
  sqlserver_data:
  chroma_data:
