"""processed_events

Revision ID: 0ebf8c3adc7b
Revises: 2258d8fea491
Create Date: 2026-07-31 22:54:24.125774

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ebf8c3adc7b"
down_revision: str | Sequence[str] | None = "2258d8fea491"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processed_events",
        sa.Column("event_id", sa.String(length=200), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("processed_events")
    # ### end Alembic commands ###
