"""orchestrator_checkpoints

Revision ID: 10c2cb8a9b6d
Revises: 0ebf8c3adc7b
Create Date: 2026-08-01 14:58:51.196783

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "10c2cb8a9b6d"
down_revision: str | Sequence[str] | None = "0ebf8c3adc7b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orchestrator_checkpoint_writes",
        sa.Column("thread_id", sa.String(length=200), nullable=False),
        sa.Column("checkpoint_ns", sa.String(length=200), nullable=False),
        sa.Column("checkpoint_id", sa.String(length=64), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column("channel", sa.String(length=200), nullable=False),
        sa.Column("write_type", sa.String(length=50), nullable=False),
        sa.Column("write_blob", sa.LargeBinary(), nullable=False),
        sa.Column("task_path", sa.String(length=500), nullable=False),
        sa.PrimaryKeyConstraint("thread_id", "checkpoint_ns", "checkpoint_id", "task_id", "idx"),
    )
    op.create_table(
        "orchestrator_checkpoints",
        sa.Column("thread_id", sa.String(length=200), nullable=False),
        sa.Column("checkpoint_ns", sa.String(length=200), nullable=False),
        sa.Column("checkpoint_id", sa.String(length=64), nullable=False),
        sa.Column("parent_checkpoint_id", sa.String(length=64), nullable=True),
        sa.Column("checkpoint_type", sa.String(length=50), nullable=False),
        sa.Column("checkpoint_blob", sa.LargeBinary(), nullable=False),
        sa.Column("metadata_type", sa.String(length=50), nullable=False),
        sa.Column("metadata_blob", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("thread_id", "checkpoint_ns", "checkpoint_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orchestrator_checkpoints")
    op.drop_table("orchestrator_checkpoint_writes")
    # ### end Alembic commands ###
