"""price_history and reference_rates

Revision ID: 2258d8fea491
Revises: 5f6884be3e52
Create Date: 2026-07-26 12:34:53.676699

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2258d8fea491"
down_revision: str | Sequence[str] | None = "5f6884be3e52"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "price_history",
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("price_date", sa.Date(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("ticker", "price_date"),
    )
    op.create_table(
        "reference_rates",
        sa.Column("series_id", sa.String(length=20), nullable=False),
        sa.Column("rate_date", sa.Date(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("series_id", "rate_date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reference_rates")
    op.drop_table("price_history")
    # ### end Alembic commands ###
