"""initial schema

Revision ID: 5f6884be3e52
Revises:
Create Date: 2026-07-25 20:58:51.911452

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5f6884be3e52"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("correlation_id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "counterparties",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "collateral_items",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("counterparty_id", sa.String(length=20), nullable=False),
        sa.Column("collateral_type", sa.String(length=20), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=True),
        sa.Column("value_usd", sa.Float(), nullable=False),
        sa.Column("haircut_pct", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["counterparty_id"],
            ["counterparties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "portfolios",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("counterparty_id", sa.String(length=20), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(
            ["counterparty_id"],
            ["counterparties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ratings",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("counterparty_id", sa.String(length=20), nullable=False),
        sa.Column("grade", sa.String(length=5), nullable=False),
        sa.Column("rating_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["counterparty_id"],
            ["counterparties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tickets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("counterparty_id", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("external_ref", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["counterparty_id"],
            ["counterparties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("portfolio_id", sa.String(length=20), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("asset_class", sa.String(length=20), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("positions")
    op.drop_table("tickets")
    op.drop_table("ratings")
    op.drop_table("portfolios")
    op.drop_table("collateral_items")
    op.drop_table("counterparties")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
