"""counterparty tier

Revision ID: 68237454ede4
Revises: 013d07246555
Create Date: 2026-08-17 19:48:25.650756

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "68237454ede4"
down_revision: str | Sequence[str] | None = "013d07246555"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "counterparties",
        sa.Column("tier", sa.String(length=20), server_default="standard", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # mssql_drop_default: SQL Server refuses to drop a column while its
    # auto-named default constraint (DF__counterpar__tier__...) exists; this
    # drops the constraint first. Ignored on Postgres. Never exercised until
    # MM-104's CI migrations job ran the first real downgrade.
    op.drop_column("counterparties", "tier", mssql_drop_default=True)
    # ### end Alembic commands ###
