"""audit log counterparty id

Revision ID: 7316c632b993
Revises: 68237454ede4
Create Date: 2026-08-19 17:03:31.183362

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7316c632b993"
down_revision: str | Sequence[str] | None = "68237454ede4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("audit_log", sa.Column("counterparty_id", sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("audit_log", "counterparty_id")
    # ### end Alembic commands ###
